- main/crypto-aes/src/main/java/org/cryptomator/crypto/aes256/FileNamingConventions.java
- main/pom.xml
- main/ui/pom.xml
- main/ui/src/main/java/org/cryptomator/ui/Main.java
- main/ui/src/main/java/org/cryptomator/ui/MainApplication.java
- main/ui/src/main/java/org/cryptomator/ui/MainController.java
- main/ui/src/main/java/org/cryptomator/ui/model/Directory.java
- main/ui/src/main/java/org/cryptomator/ui/util/ListenerRegistry.java
- main/ui/src/main/java/org/cryptomator/ui/util/SingleInstanceManager.java
- main/ui/src/main/java/org/cryptomator/ui/util/TimeoutTask.java
- main/ui/src/test/java/org/cryptomator/ui/util/ListenerRegistryTest.java
- main/ui/src/test/java/org/cryptomator/ui/util/SingleInstanceManagerTest.java
Prevents starting a second instance of the GUI and forwards
main-method-arguments to the running instance. Command line arguments
are treated by showing the corresponding folder in the GUI.
If an argument is a folder, it is shown directly. If an argument is a
.masterkey.json file, the parent directory is shown. If an argument does
not exist, but the folder can be created, the newly created folder is
shown.
It was necessary to move the main function away from the MainApplication
class because running the main method of a class, which extends the
javafx Application class, will start a non-daemon thread. This prevents
the VM from exiting naturally.
OSX needs its own mechanism, which is implemented in OS-specific code.
It is vital that the required handler is added in the main thread of the …
> Single Running Instance + Double-clicking folders/files shows in GUI

- main/ui/src/main/java/org/cryptomator/ui/model/Directory.java
- main/ui/src/main/java/org/cryptomator/ui/util/mount/FallbackWebDavMounter.java
- main/ui/src/main/java/org/cryptomator/ui/util/mount/LinuxGvfsWebDavMounter.java
- main/ui/src/main/java/org/cryptomator/ui/util/mount/MacOsXWebDavMounter.java
- main/ui/src/main/java/org/cryptomator/ui/util/mount/WebDavMounter.java
- main/ui/src/main/java/org/cryptomator/ui/util/mount/WebDavMounterStrategy.java
- main/ui/src/main/java/org/cryptomator/ui/util/mount/WindowsWebDavMounter.java
Added the new mount name to the web dav mounter interface. Under OSX, we can now use the name, which fixes #5
> Named mounting (only affects OSX atm)

- main/ui/src/main/java/org/cryptomator/ui/util/mount/LinuxGvfsWebDavMounter.java
This 'pull' fixes issues #57 using a sort of 'trial-and-error' approach.
1. The application tries to open file manager with "dav" schema name.
2. If CommandFailedException is thrown, we catch it and retry opening file manager using "webdav" schema name.
This fixes the issue with dolphin file manager and the original functionality with nautilus file manager is still working as expected.
Would love to here your comments. 
br
> w.r.t issue #57

- main/filesystem-crypto/src/main/java/org/cryptomator/crypto/engine/impl/Scrypt.java
> Cost parameter `N`, larger than 1, a power of 2 and less than `2^(128 * costParam / 8)`
didn't make any sense. It was meant to be
> Cost parameter `N`, larger than 1, a power of 2 and less than `2^(128 * blockSize / 8)`
> Fix typo in Scrypt Javadoc: `costParam` -> `blockSize`

- main/launcher/src/main/java/org/cryptomator/launcher/InterProcessCommunicator.java
Hey,
the "ipcPort.tmp" is visible by default and disturbs the aesthetics in my home dir ;)
I hope this change won't break anything. I did not test it.
Greetings
> Hide tmp file under Linux

- README.md
Updated minimum required version of Java Development Kit, because this has changed since [Cryptomator version 1.4.0](https://community.cryptomator.org/t/how-to-run-cryptomator-1-4-0-beta1-jar/1599/4). Skipping over Java 9, because [its support has already ended](http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html). Also, JCE unlimited strength policy files are [now included in the JDK by default](http://www.oracle.com/technetwork/java/javase/documentation/jdk10-readme-4419830.html#jce), so they no longer need to be mentioned separately.
> Updated minimum required version of Java Development Kit

- main/ui/src/main/java/org/cryptomator/ui/controllers/MainController.java
- main/ui/src/main/java/org/cryptomator/ui/util/DialogBuilderUtil.java
- main/ui/src/main/resources/localization/en.txt
Implemented confirmation dialog when graceful shutdown of Cryptomator fails, so that the user can try again or opt to shutdown forcefully. Implements issue #230.
> Implemented graceful shutdown confirmation dialog

- main/ui/src/main/java/org/cryptomator/ui/controllers/MainController.java
Fixed issue #771 by adding a Cancel button to the graceful shutdown dialog, so that the user can abort shutdown in case of an accident.
> Added a Cancel button to the graceful shutdown-dialog

- main/commons/src/test/java/org/cryptomator/common/EnvironmentTest.java
Fixed two failing unit tests,
* org.cryptomator.common.EnvironmentTest.testRelativeLogDir
* org.cryptomator.common.EnvironmentTest.testAbsoluteLogDir
> Fixed Environment logDir tests

- main/ui/src/main/java/org/cryptomator/ui/vaultoptions/MountOptionsController.java
The usesIndividualMountPath setting will be cleared if it bind to
an uninitialized radio button. This patch sets radio button with
current settings before binding the setting to the radio button.
> Initialize radio button before binding settings to it

- main/ui/src/main/java/org/cryptomator/ui/preferences/GeneralPreferencesController.java
- main/ui/src/main/resources/fxml/preferences_general.fxml
For platform not supporting system tray, users will have no chance to show
window and modify settings back again if the window is hidden at startup.
This is the revised version according to comments from #1025
Please see if this works for you, thanks!
> Hide startHidden setting when system tray is not supported

- main/ui/src/main/java/org/cryptomator/ui/mainwindow/MainWindowTitleController.java
When receiving close request event, main window should quit program if there is no system tray available, and just like the close button was clicked. The window close request event happens when user close window by pressing alt-f4 (Gnome) or when receiving `WM_DELETE_WINDOW` xwindow event. Current behavior is just close the window and let the program keep running, and there is no way to quit program without system tray.
The best place to handle this event should be in `MainWindowController`, but it's pretty much what the close button does in `MainWindowTitleController`. So I think it should be _okay_ to put
the handler at there.
> Handle close request event for main window

- README.md
Hi, just noticed a link was 404ing on the README, updated the URL with what I thought was equivalent on the new website.
> Update README.md, Security Architecture URL 404

- main/ui/src/main/java/org/cryptomator/ui/unlock/UnlockWorkflow.java
To reproduce the issue: do not save the vault password to the keychain ->  set `"actionAfterUnlock": "REVEAL"` -> lock the vault.
From then on, the scene to enter the password stays open on revealing the vault again.
https://github.com/cryptomator/cryptomator/blob/86906d0049d7137b5e28ad71960ec747a6a96dac/main/ui/src/main/java/org/cryptomator/ui/unlock/UnlockWorkflow.java#L100-L101
> Close unlockScene after entering the phrase and unlocking the vault

- main/buildkit/src/main/resources/launcher-linux.sh
Currently, it expects the working path to be the script path (where `libs` is located)
This allows the linux launcher to run from any path
> allows running launcher-linux.sh from any path

- main/commons/src/main/java/org/cryptomator/common/vaults/DokanyVolume.java
This fixes part of #1033 by shortening the FS_TYPE_NAME so that it can be returned inside a 48-byte-long FILE_FS_ATTRIBUTE_INFORMATION buffer, which only has room for up to 17 UTF-16 characters in the file system name field.
> shorten FS_TYPE_NAME  to "CryptomatorFS"

- main/ui/src/main/java/org/cryptomator/ui/fxapp/FxApplication.java
- main/ui/src/main/java/org/cryptomator/ui/fxapp/FxApplicationModule.java
- main/ui/src/main/java/org/cryptomator/ui/quit/QuitComponent.java
- main/ui/src/main/java/org/cryptomator/ui/quit/QuitController.java
- main/ui/src/main/java/org/cryptomator/ui/quit/QuitModule.java
This fixes #1323 
It is implementing by adding a check mechanism in the quit dialogue creation method of the `FxApplication` class.
A considered alternative was create a singleton object between the `FxApplication` and the `QuitComponent`, which preserves the state of the quit window, and inject this object into FxApplication.
> Show only one quit dialogue at a time

- .idea/runConfigurations/Cryptomator_Linux.xml
- .idea/runConfigurations/Cryptomator_Linux_Dev.xml
- .idea/runConfigurations/Cryptomator_Windows.xml
- .idea/runConfigurations/Cryptomator_Windows_Dev.xml
- .idea/runConfigurations/Cryptomator_macOS.xml
- .idea/runConfigurations/Cryptomator_macOS_Dev.xml
- main/commons/src/main/java/org/cryptomator/common/Environment.java
- main/commons/src/main/java/org/cryptomator/common/settings/Settings.java
- main/commons/src/main/java/org/cryptomator/common/settings/SettingsJsonAdapter.java
- main/commons/src/main/java/org/cryptomator/common/settings/SettingsProvider.java
- main/commons/src/test/java/org/cryptomator/common/EnvironmentTest.java
- main/commons/src/test/java/org/cryptomator/common/settings/SettingsJsonAdapterTest.java
- main/commons/src/test/java/org/cryptomator/common/settings/SettingsTest.java
- main/ui/src/main/java/org/cryptomator/ui/fxapp/FxApplication.java
- main/ui/src/main/java/org/cryptomator/ui/fxapp/FxApplicationComponent.java
- main/ui/src/main/java/org/cryptomator/ui/launcher/AppLaunchEventHandler.java
- main/ui/src/main/java/org/cryptomator/ui/launcher/AppLifecycleListener.java
- main/ui/src/main/java/org/cryptomator/ui/launcher/FxApplicationStarter.java
- main/ui/src/main/java/org/cryptomator/ui/launcher/UiLauncher.java
- main/ui/src/main/java/org/cryptomator/ui/launcher/UiLauncherModule.java
- main/ui/src/main/java/org/cryptomator/ui/mainwindow/MainWindowComponent.java
- main/ui/src/main/java/org/cryptomator/ui/mainwindow/MainWindowTitleController.java
- main/ui/src/main/java/org/cryptomator/ui/preferences/GeneralPreferencesController.java
- main/ui/src/main/java/org/cryptomator/ui/traymenu/TrayIconController.java
- main/ui/src/main/java/org/cryptomator/ui/traymenu/TrayMenuComponent.java
- main/ui/src/main/java/org/cryptomator/ui/traymenu/TrayMenuController.java
- main/ui/src/main/resources/fxml/main_window_title.fxml
- main/ui/src/main/resources/fxml/preferences_general.fxml
- main/ui/src/main/resources/i18n/strings.properties
Basically this adds two more options to the general Preferences:
* Control whether a tray icon should be installed, which should relax the situation where the Desktop environment doesn't necessarily act in favour of AWT tray icons, thus causing problems such as #1113, #1078, #1079
* Control whether the main window should show a minimize button (which fixes #1179)
* Also, it is now possible to start with the Window minimized by disabling the tray icon and asking to start hidden at the same time. This may also solve #1344
It is worth mentioning, that the minimize button is still obligatory when no tray icon exists, in which case the corresponding checkbox will be invisible.
This also rewires interactions between the Dagger components Launcher, TrayMenu and FxApplication.
> Add Minimize Button

- main/ui/src/main/java/org/cryptomator/ui/unlock/UnlockWorkflow.java
Fixes #1519
Currently clicking "Back" in the `invalidMountPointScene` causes a filled out "Enter Password" Window to appear, even if the password was entered by the keychain and not by the user. Fixing this requires additional refactoring to the `invalidMountPointScene` controller.
I'm under the impression that fully refactoring `invalidMountPointScene` after the example of `ErrorComponent` would be a good solution at this point in time.
> Fixed suppressed "invalid mountpoint" messages

- main/ui/src/main/java/org/cryptomator/ui/mainwindow/VaultDetailLockedController.java
- main/ui/src/main/java/org/cryptomator/ui/vaultoptions/SelectedVaultOptionsTab.java
- main/ui/src/main/java/org/cryptomator/ui/vaultoptions/VaultOptionsComponent.java
- main/ui/src/main/java/org/cryptomator/ui/vaultoptions/VaultOptionsController.java
- main/ui/src/main/java/org/cryptomator/ui/vaultoptions/VaultOptionsModule.java
- main/ui/src/main/resources/fxml/vault_detail_locked.fxml
- main/ui/src/main/resources/fxml/vault_options.fxml
- main/ui/src/main/resources/i18n/strings.properties
These are, in my opinion, minimal changes to make the feature "save password" clearer:
- Changed label from "Save Password" to "Remember Password" in unlock dialog.
- Switched placements of "Vault Options" hyperlink (and made it to a button) and "Password saved" label in vault detail locked screen.
Other changes considered but omitted:
- Changing the localization key to `unlock.rememberPassword`. I wasn't sure if this would be helpful or hurtful.
- Making the label "Password saved" to a hyperlink, which would deep-link to the "Password" tab of the "Vault Options". These would require bigger changes, should this be part of this PR?
- Adding a detail text to the "Remember Password" checkbox with something like "Saves the password on this machine, so you don't need to enter it on subsequent …
> "Save Password" Clarification

- main/ui/src/main/java/org/cryptomator/ui/mainwindow/MainWindowModule.java
- main/ui/src/main/java/org/cryptomator/ui/mainwindow/VaultListContextMenuController.java
- main/ui/src/main/java/org/cryptomator/ui/mainwindow/VaultListController.java
- main/ui/src/main/resources/fxml/vault_list.fxml
- main/ui/src/main/resources/fxml/vault_list_cell.fxml
- main/ui/src/main/resources/fxml/vault_list_contextmenu.fxml
- main/ui/src/main/resources/i18n/strings.properties
This PR fixes a bug and improves the context menu.
Currently the context menu of the vault list only exists to remove a vault. This a very thin feature list for a context menu, hence, it should be either removed (and vault removable moved to somewhere else in the gui) or its functionality extended. In this PR the latter is done. From the context menu a user can select now common vault tasks, depening on the vault state:
Also, closes #1478
> Feature: Make Context menu Great Again 

- main/ui/src/main/java/org/cryptomator/ui/mainwindow/MainWindowTitleController.java
- main/ui/src/main/java/org/cryptomator/ui/preferences/GeneralPreferencesController.java
- main/ui/src/main/java/org/cryptomator/ui/preferences/PreferencesController.java
- main/ui/src/main/java/org/cryptomator/ui/preferences/PreferencesModule.java
- main/ui/src/main/java/org/cryptomator/ui/preferences/SelectedPreferencesTab.java
- main/ui/src/main/java/org/cryptomator/ui/preferences/SupporterCertificateController.java
- main/ui/src/main/resources/fxml/preferences.fxml
- main/ui/src/main/resources/fxml/preferences_contribute.fxml
- main/ui/src/main/resources/fxml/preferences_general.fxml
- main/ui/src/main/resources/i18n/strings.properties
This PR contains the migration from the term "donation key" to "supporter certificate".
> Rename Donation Key to Supporter Certificate

- main/ui/src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultLocationController.java
- main/ui/src/main/resources/fxml/addvault_new_location.fxml
- main/ui/src/main/resources/i18n/strings.properties
Unified design (compare it with the choose-password-screen), better error messages, higher focus on the storage path.
Includes:
* more checks of the chosen vault path
* every check has own error message
* perform checks when vault path changes
* if any radio button selected, enable vault path field (no-edit)
No path selected:
If specified path is suitable for vault storage:
Example for an error:
> Rework choose-location-screen in add vault wizard:

- main/ui/src/main/java/org/cryptomator/ui/addvaultwizard/AddVaultModule.java
- main/ui/src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultPasswordController.java
- main/ui/src/main/java/org/cryptomator/ui/changepassword/ChangePasswordController.java
- main/ui/src/main/java/org/cryptomator/ui/changepassword/ChangePasswordModule.java
- main/ui/src/main/java/org/cryptomator/ui/common/NewPasswordController.java
- main/ui/src/main/java/org/cryptomator/ui/controls/SecurePasswordField.java
- main/ui/src/main/java/org/cryptomator/ui/recoverykey/RecoveryKeyModule.java
- main/ui/src/main/java/org/cryptomator/ui/recoverykey/RecoveryKeyResetPasswordController.java
- main/ui/src/main/resources/fxml/addvault_new_password.fxml
- main/ui/src/main/resources/fxml/changepassword.fxml
- main/ui/src/main/resources/fxml/recoverykey_reset_password.fxml
This PR removes string properties to pass a user password between different controllers and directly access password fields from included fxml files.
While this increase the coupling between two JavaFX controllers, in this context this is quite natural, since in every case of the applied changes one controller contains the "new password" controller. Hence there is no need to create an artificial property just to pass the passphrase between those two, the password can directly be read by using the builtin field injection of JavaFX.
> Simplify password creation

- main/commons/src/main/java/org/cryptomator/common/vaults/Vault.java
- main/ui/src/main/java/org/cryptomator/ui/keyloading/KeyLoadingModule.java
To get the unverfied config of a vault the method `Vault::loadVaultConfig` exists. It returns `Optional<UnverifiedVaultConfig>`, such that it can be used within the Dagger graph.
This PR changes the method signature to directly return the unverified config and throws an exception on failure. This has the advance, that the stacktrace of the error is preserved. Additionally, one can directly react to an error and do not has to work around the Optionals wrapping.
To address the dagger concerns, inside the key loading module the keyID is not extracted in an extra method, but directly when choosing the appropiate key provider. The drawback of this approach is, that the keyID cannot be injected directly for future uses.
> method loadVaultConfig() throws exception instead of returning optional

- main/commons/src/test/java/org/cryptomator/common/settings/VaultSettingsJsonAdapterTest.java
**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution.
**Solution:**
Using JUnit's grouped assertions feature, all assertions are executed, and all failures will be reported together. In this refactoring, no original assertion was changed.
**Result:**
_Before:_
```
Assertions.assertEquals("foo", vaultSettings.getId());
Assertions.assertEquals(Paths.get("/foo/bar"), vaultSettings.path().get());
Assertions.assertEquals("test", vaultSettings.displayName().get());
Assertions.assertEquals("X", vaultSettings.winDriveLetter().get());
Assertions.assertEquals("/home/test/crypto", vaultSettings.customMountPath().get());
Assertions.assertEquals("--foo --bar", vaultSettings.mountFlags().get());
``` …
> Improved grouped assertions

- README.md
On reworking ['Single maven module'](https://github.com/cryptomator/cryptomator/commit/7fac6da4485366f9b649b12d73b1d55e84c34204) you missed one little bit in the README.md.
> Instruction for building on the CLI have a slight error

- .github/workflows/build.yml
As some users build this project from source using a package manager like `pacman` on arch based linux distros, we could provide a  GPG signature next to the source tarball, so that those package managers can automatically verify the signature of the downloaded sources and not check the SHA256 provided by the packager.
With this PR, a `cryptomator-${{ github.ref }}.tar.gz.asc` file e.g. `cryptomator-1.6.0.tar.gz.asc` will be added to the release assets.
> Sign tarball in release using GPG

- .github/workflows/release.yml
This replaces the formerly used version `99.0.0` for manually triggered prerelease builds.
A prerelease version number should be greater than the old stable version but lower than the next stable release. E.g. `1.0.0 ≤ 1.1.0-beta1 ≤ 1.1.0`. The correct version string should therefore be a required param when triggering a build.
> Provide version string when manually triggering a build

- dist/linux/appimage/build.sh
The `dist/linux/appimage/build.sh` file fails to build an app image the way it is.
I found the changes in this Pull Request from `.github/workflows/release.yml`.
> Including pluginDir to linux/appimage/build.sh

- .github/workflows/release.yml
- dist/linux/debian/changelog
OpenJDK 17 is available on Ubuntu Bionic, so we should be able to build the PPA version of Cryptomator 1.6.x for Bionic as well.
If this experiment succeeds, this fixes #1905. It should be tested using [the `cryptomator-beta` PPA](https://launchpad.net/~sebastian-stenzel/+archive/ubuntu/cryptomator-beta/+packages)
We can then copy binaries from Bionic to Focal (and newer releases), assuming there are no breaking changes in dependencies.
> PPA build for Ubuntu Bionic

- src/main/java/org/cryptomator/ui/common/UserInteractionLock.java
- src/main/java/org/cryptomator/ui/lock/LockForcedController.java
- src/main/java/org/cryptomator/ui/lock/LockModule.java
- src/main/java/org/cryptomator/ui/lock/LockWorkflow.java
- src/main/resources/fxml/lock_forced.fxml
- src/main/resources/i18n/strings.properties
This fixes #1934, essentially by adding a retry loop:
Furthermore this adds a (graceful) retry button:
> Handle exception when force-locking

- .github/workflows/release.yml
This solves an issue with the `jlinked` runtime based on `OpenJDK Runtime Environment Zulu17.30+51-CA (build 17.0.1+12-LTS)`, which results during launch on macOS:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Hash of javafx.base (3af64106ce76d7e0b3d38ae5a5d89f7ddf5d0109e0b0088b6e392847a462cc13) differs to expected hash (d75b7ed00f1b64bc63be63af589e2469f152516d447877894ff1bfd147bdba3b) recorded in java.base
```
Furthermore, we no longer need a `cache` step, as this is now supported with the newer `setup-java` action.
> Update actions/setup-java and use Temurin in release builds

- dist/win/build.bat
- dist/win/build.ps1
- dist/win/contrib/patchHosts.bat
- dist/win/contrib/patchHosts.ps1
- dist/win/resources/main.wxs
This re-adds a workaround to the .msi installer, that we [introduced in version 1.3.0](https://cryptomator.org/blog/2017/07/01/release-1.3.0/#windows).
A new script is added to the installation dir, which will be invoked during installation with elevated permissions. If not already present, it'll add an entry to Windows' hosts file.
> Add `cryptomator-vault` alias to etc/hosts during (re)install

- src/main/java/module-info.java
- src/main/java/org/cryptomator/ui/keyloading/hub/AuthFlowController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/CreateDeviceDto.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingModule.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingStrategy.java
- src/main/java/org/cryptomator/ui/keyloading/hub/ReceiveKeyController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/RegisterDeviceController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/UnauthorizedDeviceController.java
- src/main/resources/fxml/hub_register_device.fxml
Instead of displaying a hyperlink leading to browser-based device registration form, this change adds an integrated device registration form.
This way, you can't trick a user to register a spoofed public key via manipulated links, eliminating the need for a paring code.
The UI is still very experimental, though.
> Register device from within client application

- .github/workflows/release.yml
- dist/linux/appimage/build.sh
- dist/linux/debian/copyright
- dist/linux/debian/rules
- dist/mac/dmg/build.sh
- dist/mac/dmg/resources/license.rtf
- dist/win/build.ps1
- dist/win/resources/license.rtf
- src/main/resources/fxml/preferences_about.fxml
I went through the various license files and UI files and updated the outdated "(C) 2016 - 2021 Skymatic GmbH" to "(C) 2016 - 2022 Skymatic GmbH".
> Update copyright years from 2021 to 2022 to reflect the new year

- .gitignore
- pom.xml
- src/main/resources/license/THIRD-PARTY.txt
Updating JavaFX inside Maven to 17.0.2 to fix [JDK-8275723](https://bugs.openjdk.java.net/browse/JDK-8275723). This is only relevant for development on a Mac with an M1 processor.
> Update JavaFX to 17.0.2

- .github/workflows/release.yml
- dist/linux/appimage/build.sh
- dist/linux/debian/rules
- dist/mac/dmg/build.sh
- dist/win/build.ps1
This adds the modules we need to instruct users to dump us a JFR recording. This came up in the context of issue #1269.
This adds roughly 600 kiB to the application, which seems tolerable.
> Add modules required for JFR

- dist/linux/common/org.cryptomator.Cryptomator.metainfo.xml
The shots do appstream-util validate.
To use the new screenshots for flathub, we need to merge this PR and update this hash afterwards:
https://github.com/flathub/org.cryptomator.Cryptomator/blob/f11f3f9ffdf507194758b73b7771f12c4afc0c10/org.cryptomator.Cryptomator.yaml#L95
> Update Cryptomator screenshots for flathub, taken of 1.6.5

- src/main/java/org/cryptomator/ui/traymenu/TrayMenuController.java
Closes #1583.
This PR adds the unlock status to the name of the vault in the tray. It adds `*` as a prefix to each unlocked vault. I tried it as a suffix like it was described in the issue but the marker is less obvious since the name of each vault is not consistent.
With this new feature, it's easier than ever to find exactly which vaults are unlocked with a visual marker in the list.
Here's an example with `testvault` as an unlocked vault and `testvault2` as a locked fault.
> Show vault locked/unlocked state in the vault title in the tray menu

- src/main/java/org/cryptomator/common/settings/UiTheme.java
- src/main/java/org/cryptomator/ui/preferences/GeneralPreferencesController.java
- src/main/java/org/cryptomator/ui/preferences/InterfacePreferencesController.java
- src/main/java/org/cryptomator/ui/preferences/PreferencesController.java
- src/main/java/org/cryptomator/ui/preferences/PreferencesModule.java
- src/main/java/org/cryptomator/ui/preferences/SelectedPreferencesTab.java
- src/main/resources/fxml/preferences.fxml
- src/main/resources/fxml/preferences_about.fxml
- src/main/resources/fxml/preferences_contribute.fxml
- src/main/resources/fxml/preferences_general.fxml
- src/main/resources/fxml/preferences_interface.fxml
- src/main/resources/fxml/preferences_updates.fxml
- src/main/resources/fxml/preferences_volume.fxml
- src/main/resources/i18n/strings.properties
This moves L&F-related settings from "General" to its own preferences tab. This declutters not only the interface but also the code the attached controllers.
The freed up space in "General" might be used to integrate the sparse "Virtual Drive" settings again, but this should be a separate PR.
> Moved interface preferences to its own tab

- pom.xml
- src/main/java/org/cryptomator/ui/fxapp/FxApplicationStyle.java
Compile our JavaFX themes into `.bss` files, which should load slightly faster.
> Prefer binary stylesheets

- .github/workflows/dl-stats.yml
Adds a workflow that runs every 15 minutes:
Query download counts of most recent non-prerelease releases and report them to Graphite.
> Report Download Stats

- .github/workflows/win-exe.yml
Merging this PR will on every release automatically create a PR in the Windows Package Manager Community repository (https://github.com/microsoft/winget-pkgs), updating to the latest MSI build by the release.
It is based on [this article](https://www.techwatching.dev/posts/wingetcreate).
What is still required for a successful run:
> Add automatic release to winget to msi/exe ci job

- src/main/java/org/cryptomator/common/LocationPreset.java
- src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultLocationController.java
- src/main/java/org/cryptomator/ui/addvaultwizard/ObservedLocationPresets.java
- src/main/resources/fxml/addvault_new_location.fxml
With this PR the formerly used `LocationPresets` class is just an observable wrapper for the new `LocationPreset` enum, which encapsulates for different cloud storage providers their normally used local paths.
> Enumeenize well-known local cloud storage paths

- .github/workflows/mac-dmg.yml
Replaced custom steps with [`xcode-notarization-action`](https://github.com/cocoalibs/xcode-notarization-action).
Secrets `MACOS_NOTARIZATION_KEYCHAIN_PROFILE` and `MACOS_NOTARIZATION_TMP_KEYCHAIN_PW` are no longer required after merging.
Tested in [this build](https://github.com/cryptomator/cryptomator/runs/6607664627?check_suite_focus=true#step:17:1).
> Use Xcode Notarization Action

- src/main/java/org/cryptomator/common/CatchingExecutors.java
- src/main/java/org/cryptomator/common/CommonsModule.java
Closes #2258.
**Considerations:**
Tasks submitted via ThreadPoolExecutor/ScheduledThreadPoolExecutor do not call the UncaughtExceptionHandler of the underlying threads. Exceptions are expected to be processed using [Future#get().](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Future.html#get())
Since Future#get() is blocking, this approach is not feasible in many instances, especially not in the particular case of AutoLocker#tick().
The JDK also [offers a different approach](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html#afterExecute(java.lang.Runnable,java.lang.Throwable)) to handling exceptions, which was implemented here.
> Added catching executors

- src/main/java/org/cryptomator/ui/common/FxmlFile.java
- src/main/java/org/cryptomator/ui/keyloading/hub/AuthFlowController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingModule.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingStrategy.java
- src/main/java/org/cryptomator/ui/keyloading/hub/ReceiveKeyController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/RegisterDeviceController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/RegisterFailedController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/RegisterSuccessController.java
- src/main/resources/fxml/hub_auth_flow.fxml
- src/main/resources/fxml/hub_receive_key.fxml
- src/main/resources/fxml/hub_register_device.fxml
- src/main/resources/fxml/hub_register_failed.fxml
- src/main/resources/fxml/hub_register_success.fxml
- src/main/resources/fxml/hub_unauthorized_device.fxml
- src/main/resources/i18n/strings.properties
WIth this PR the new dialogs required for the hub project are adjusted to the new designed fixed in #2311 and their texts are added to the translations file.
Additionally, two new dialogs are added to give the user better feedback.
> Improve Hub dialogs

- src/main/java/org/cryptomator/ui/keyloading/hub/RegisterDeviceController.java
- src/main/resources/fxml/hub_register_device.fxml
- src/main/resources/i18n/strings.properties
Improvement for the device registration workflow. A message below the textbox is shown, if the device name is already used for that user in the Hub instance. The message is hidden, when the user changes the text.
> Display Label when device name alread in use 

- .github/workflows/win-exe.yml
- .idea/runConfigurations/Cryptomator_Windows.xml
- .idea/runConfigurations/Cryptomator_Windows_Dev.xml
- dist/win/build.ps1
- pom.xml
- src/main/java/org/cryptomator/common/Constants.java
- src/main/java/org/cryptomator/common/Environment.java
- src/test/java/org/cryptomator/common/EnvironmentTest.java
Closes #2260 
The new library version renamed a JVM property, which is used in Cryptomator. I renamed (assumingly) all occurences of that property.
> Update integrations-win lib

- src/main/java/org/cryptomator/ui/common/FxmlFile.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingModule.java
- src/main/java/org/cryptomator/ui/keyloading/hub/LicenseExceededController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/ReceiveKeyController.java
- src/main/resources/fxml/hub_license_exceeded.fxml
- src/main/resources/i18n/strings.properties
This PR enables handling a 402 response from the hub instance within the ui:
> handle 402 error when authenticating with Cryptomator Hub

- .github/workflows/win-exe.yml
- .github/workflows/winget.yml
With this PR the winget release task is refactored into its own workflow file. It is designed as a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow), so that the old build script can conveniently call it. Additionally, it can be called manually.
It was refactored out for two reasons:
* winget release task depends on _the download URL_ of the uploaded release artifact, not the build artifact itself
* manual trigger is possible without wasting cpu time or any flags to switch off other jobs
> Refactor winget release to own workflow file

- .github/workflows/debian.yml
- dist/linux/debian/changelog
- dist/linux/debian/control
- dist/linux/debian/rules
This increases the minimum supported Ubuntu version to 20.04.
> Use `coffeelibs-jdk-19` during PPA build

- .github/workflows/build.yml
- .github/workflows/release-check.yml
This PR moves the check for required prerelease changes to it's own worklfow file.
With this change, release branches can normally pass CI without the requirement to enforce the validation success by all means (i.e. add fake info to a version file).
Before merging, the a branch protection rule for the main branch must be activated with the following settings:
Note: the status check has to match the name field of the job in the release-check.yml file.
> Move release precondition checks to own workflow

- .github/workflows/win-exe.yml
- dist/win/build.bat
- dist/win/build.ps1
- dist/win/contrib/patchWebDAV.bat
- dist/win/resources/main.wxs
- dist/win/resources/overrides.wxi
- src/main/java/org/cryptomator/common/Environment.java
- src/main/java/org/cryptomator/common/vaults/WebDavVolume.java
This PR allows to set/overwrite more values of the windows installer during build, making the build easier to adapt to changes.
Affected parts are:
* Alias of the loopback device/localhost
* Legacy installation check
* Media type and file extension of encrypted data
* Name of application executable blocking installation
> Windows Installer: Parameterize Hardcoded Values

- src/main/java/org/cryptomator/ui/addvaultwizard/ChooseExistingVaultController.java
- src/main/java/org/cryptomator/ui/fxapp/FxApplicationStyle.java
In order to prevent code duplication, I added an observable property in [`FxApplicationStyle`](https://github.com/cryptomator/cryptomator/blob/fbe33e21fba3cebdfbf8552e712d5198109ea5a1/src/main/java/org/cryptomator/ui/fxapp/FxApplicationStyle.java) to determine the _actually_ applied theme. Or is there any better way to fix this issue?
Fixes #2512. Should replace #2514.
> Fixes wrong screenshot shown in Open Existing Vault

- .github/workflows/appimage.yml
- .github/workflows/debian.yml
- .github/workflows/mac-dmg.yml
- .github/workflows/win-exe.yml
- dist/linux/debian/control
- dist/linux/debian/rules
- pom.xml
Instead of .jars, we now use jmods for `jlink`.
TODO @infeo this solves some problems. And is recommended (see link to openjfx mailing list?)
> Use OpenJFX jmods

- src/main/java/org/cryptomator/ui/common/FxmlFile.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingModule.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubKeyLoadingStrategy.java
- src/main/java/org/cryptomator/ui/keyloading/hub/NoKeychainController.java
- src/main/resources/fxml/hub_no_keychain.fxml
- src/main/resources/i18n/strings.properties
Fixes #2597.
This PR adds an end dialog the the hub unlock flow, if the keychain is disabled.
The dialog explains shortly, why the keychain is required and offers a button to open the general preferences.
> Feature: Show dialog for hub vaults, if keychain is disabled

- src/main/java/org/cryptomator/ui/traymenu/AwtTrayMenuController.java
Follow-up on: [#2489](https://github.com/cryptomator/cryptomator/pull/2489#issuecomment-1398575771)
It's a simple fix on macOS but I wanted to make sure it also works on Windows.
Edit: Confirmed at https://github.com/cryptomator/cryptomator/pull/2489#issuecomment-1399419068
> Fixed vault list refresh when tray icon is clicked on macOS

- src/main/java/org/cryptomator/common/ObservableUtil.java
- src/main/java/org/cryptomator/common/mount/MountModule.java
- src/main/java/org/cryptomator/ui/preferences/VolumePreferencesController.java
- src/main/resources/css/dark_theme.css
- src/main/resources/css/light_theme.css
- src/main/resources/fxml/preferences_volume.fxml
- src/main/resources/i18n/strings.properties
Closes #2786.
Adds some ugly workaround code, but increases UX for most of the users.
FUSE-T and macFUSE cannot be used in the same JVM due to loading the same symbols from different shared libraries and the inability to unload a shared library once loaded.
Workaround is as follows: In the UI, the user will be notified that the apps must be restartet if she switches from macFuse to FUSE-T (or vice versa). The change is still written to the settings file, but in the model, the change is blocked.
> Feature: Only require app restart if switching between macFUSE and FUSE-T

- src/main/java/org/cryptomator/launcher/Cryptomator.java
- src/main/java/org/cryptomator/launcher/SupportedLanguages.java
- src/main/java/org/cryptomator/ui/preferences/InterfacePreferencesController.java
- src/test/java/org/cryptomator/launcher/SupportedLanguagesTest.java
> List of languages should have system default, English and then all other languages in alphabetic order.
> That is, in alphabetic order with respect to the language the list is localized in (seems to be English always)
Fixes #2813
> Respect user's locale when sorting language list

- src/main/java/org/cryptomator/ui/fxapp/AutoUnlocker.java
- src/main/java/org/cryptomator/ui/fxapp/FxApplication.java
I noticed that the auto unlock of a vault on pCloud does not always work. This is because pCloud starts later then Cryptomator on my system and thus the vault directory does not exist, resulting in a missing vault state. I also found [this](https://community.cryptomator.org/t/pcloud-cryptomator-unlock-vault-when-starting-cryptomator-not-automated-on-startup/9812) on the forum which suggests a workaround for a delayed start. Instead of a delayed start, I made a check that runs periodically to see if the vault directory exists. If the vault directory exists then the vault state is updated and unlocked. When there are no more missing vaults, the periodic check stops.
The problem can easily be reproduced by creating a vault on a USB drive. Start Cryptomator without the USB attached so the …
> Auto unlock vaults that were missing at startup

- src/main/java/org/cryptomator/common/mount/MountPointInUseException.java
- src/main/java/org/cryptomator/common/mount/Mounter.java
- src/main/java/org/cryptomator/ui/unlock/UnlockInvalidMountPointController.java
- src/main/resources/i18n/strings.properties
- suppression.xml
> Show a dedicated message when mounting to an occupied Windows drive

- .github/workflows/mac-dmg.yml
- dist/mac/dmg/build.sh
Fixes #3030.
This PR replaces in the CI script the Zulu JVM+FX by Temurin JVM and downloads in a seperate step JFX jmods from Gluon. Additionally, the local build script is adjusted to work out-of-the-box again by also adding a step downloading the jmods.
> CI: Use Temurin JVM+JFX Jmods from Gluon instead of Zulu JVM+FX

- src/main/java/org/cryptomator/ui/fxapp/UpdateCheckerModule.java
For reasons of unified APIs, this URL is now https://api.cryptomator.org/desktop/latest-version.json
> Change update check URL

- src/main/java/org/cryptomator/ui/error/ErrorController.java
When things go wrong, we don't always want to leak user IPs to GitHub, so we now use our proxy instead.
> Change error codes URL

- src/main/java/org/cryptomator/ui/error/ErrorController.java
As an addition to Issue [#3060](https://github.com/cryptomator/cryptomator/pull/3060), this pull request extends the HTTP request to api.cryptomator.org/desktop/error-codes.json by adding the 'error-code' parameter with the current error code as follows:
`api.cryptomator.org/desktop/error-codes.json?error-code=####%3A####%3A####`
Furthermore, we've added a 'User-Agent' header to the HTTP request, including the product version, build flavor, os, os version and cpu architecture.
> Enhance user agent string when downloading error code database

- .github/workflows/debian.yml
- dist/linux/debian/rules
- src/main/java/org/cryptomator/common/Environment.java
- src/main/java/org/cryptomator/ui/fxapp/FxApplication.java
- src/main/java/org/cryptomator/ui/fxapp/UpdateChecker.java
- src/main/java/org/cryptomator/ui/preferences/PreferencesController.java
This adds a new system property `cryptomator.disableUpdateCheck` which (when set) will
* disable version checks
* disable the update reminder (#2998)
* removes the updates tab from the preferences window
Furthermore, it sets this property for PPA builds, as updates will be handled externally via `apt`.
fixes #3117
> Disable Update Check

- dist/linux/appimage/build.sh
These are the changes:
- follow up of https://github.com/cryptomator/cryptomator/issues/3102: Build for aarch64 too; the script determines the architecture and builds, considering the architecture
- added `set -e` at the top, that causes the script to stop on an error instead of continuing; this makes it easier to find errors, once the script is running, and it now only shows _success_ at the end, when the AppImage truly was built
> Improve AppImage build script

- .github/workflows/error-db.yml
When we delete a discussion, it is not currently propagated against the error database, which means that Cryptomator thinks there is a solution to a problem, but when it is opened in GitHub it shows a 404.
https://github.com/cryptomator/cryptomator/commit/109f5d1faa1057884445ed16f0b9c16d54dfe845 was not enough to fix this, because the query against the discussion repo simply fails because the entry does not exists anymore.
This PR implements the deletion of the discussion to be propagated against the error database.
> Propagate deleted discussions to the error database

- src/main/java/org/cryptomator/ui/mainwindow/VaultListController.java
Closes #3155 : Toggle vault lock status by double-clicking on it on the vault list of the main window.
PS: I tried to do idiomatic and clean code, don't hesitate to ask for changes if needed
> Feature: Double click on a vault in the list to unlock it

- README.md
This addresses #3277 . It is a one-line change in the README so that new devs won't trip over the same stone again.
I also noticed in commit 4043e3f71f9f2dd908814a54700ae0e52582e163 where the JDK bump happens, Zulu becomes the preferred flavor in GH actions env. Thus I have appended `zulu` to the JDK flavor example list as well.
- cryptomator develop branch, as of now, compiles fine with Zulu JDK 21 arm64:
```bash
brew tap mdogan/zulu
brew install zulu-jdk21
export JAVA_HOME="$(/usr/libexec/java_home -v 21)"
```
```bash
$ mvn -version     
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 21.0.1, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
Default locale: …
```
> Bump README's build dependency JDK version from 19 to 21

- dist/linux/common/org.cryptomator.Cryptomator.metainfo.xml
Closes https://github.com/flathub/org.cryptomator.Cryptomator/issues/77.
See https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#brand-colors.
The colours set with this PR can be checked with the [banner preview](https://docs.flathub.org/banner-preview/).
I've taken them from the Cryptomator main web page. They look like this:
> Add coloured banners for app in Flathub store

- .github/workflows/appimage.yml
- .github/workflows/build.yml
- .github/workflows/check-jdk-updates.yml
- .github/workflows/debian.yml
- .github/workflows/dependency-check.yml
- .github/workflows/get-version.yml
- .github/workflows/mac-dmg.yml
- .github/workflows/pullrequest.yml
- .github/workflows/release-check.yml
- .github/workflows/win-exe.yml
- .idea/misc.xml
- dist/linux/appimage/build.sh
- dist/linux/debian/control
- dist/linux/debian/rules
- dist/mac/dmg/build.sh
- dist/win/build.ps1
- pom.xml
- src/main/java/module-info.java
This PR updates the project to use/require JDK 22.
Fixes #3376 and #3382.
I did not remove the --enable-preview flag, since i'm not sure if we already use the String template processors somewhere.
> Feature: JDK22

- .github/workflows/appimage.yml
- .github/workflows/debian.yml
- .github/workflows/mac-dmg.yml
- .github/workflows/win-exe.yml
- dist/linux/appimage/build.sh
- dist/mac/dmg/build.sh
- dist/win/build.ps1
- pom.xml
We cannot update the Java 21 LTS version, since there are no more linux aarch64 artifacts released for it.
> Feature: Update to jfx22

- src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultPasswordController.java
This PR adds a postprocessing step when creating new vaults.
This step is added to prevent users stepping into #2880.
An upgrade of this feature would be to add a UI dropdown in the expert settings with a property handed over the vault creation, but i decided to go for the slim solution.
> Mitigates #2880

- pom.xml
- src/main/java/module-info.java
This PR
* updates dagger to the latest version
* adds jakarta-inject-api as a dependency and
* removces guava as a dependency
Guava is not used anymore in the project. ` jakarta-inject-api` is required with updating dagger to 2.52, see also https://github.com/google/dagger/issues/4391.
> Cleanup: Dagger+Guava dependencies

- src/main/java/org/cryptomator/common/settings/Settings.java
- src/main/java/org/cryptomator/common/settings/SettingsJson.java
- src/main/java/org/cryptomator/ui/mainwindow/VaultListCellController.java
- src/main/java/org/cryptomator/ui/mainwindow/VaultListController.java
- src/main/java/org/cryptomator/ui/preferences/InterfacePreferencesController.java
- src/main/resources/fxml/preferences_interface.fxml
- src/main/resources/fxml/vault_list.fxml
- src/main/resources/fxml/vault_list_cell.fxml
- src/main/resources/i18n/strings.properties
This PR introduces the ability to display the vault list in a compact view.
The option can be found under Preferences > Interface with the label "Enable compact vault list". When enabled, the vault list is displayed in a more condensed format, and the display is updated immediately.
> Feature: Add Option to Enable Compact Vault List View

- .github/workflows/appimage.yml
- .github/workflows/build.yml
- .github/workflows/check-jdk-updates.yml
- .github/workflows/debian.yml
- .github/workflows/dependency-check.yml
- .github/workflows/get-version.yml
- .github/workflows/mac-dmg.yml
- .github/workflows/pullrequest.yml
- .github/workflows/release-check.yml
- .github/workflows/win-exe.yml
- .idea/misc.xml
- dist/linux/debian/rules
- pom.xml
- src/main/java/org/cryptomator/common/locationpresets/GoogleDriveMacLocationPresetsProvider.java
- src/main/java/org/cryptomator/common/mount/Mounter.java
- src/main/java/org/cryptomator/ui/keyloading/hub/HubConfig.java
- src/main/java/org/cryptomator/ui/keyloading/hub/ReceiveKeyController.java
- src/main/java/org/cryptomator/ui/keyloading/hub/RegisterDeviceController.java
This PR builds on top of #3621 and updates the used JDK to version 23.
A search revealed, that no library we use requires the `--enable-preview` flag anymore, we only have to update this repo and downstream.
TODOs:
> Feature: JDK 23

- .github/workflows/appimage.yml
`--sign-args` is an unsupported argument, however it is not strictly required in our case.
According to https://github.com/AppImage/appimagetool/issues/39, it is not planned to re-add it, even though it is still documented.
> fix appimage build

- src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultExpertSettingsController.java
- src/main/java/org/cryptomator/ui/mainwindow/WelcomeController.java
- src/main/java/org/cryptomator/ui/migration/MigrationImpossibleController.java
- src/main/java/org/cryptomator/ui/preferences/VolumePreferencesController.java
- src/main/java/org/cryptomator/ui/wrongfilealert/WrongFileAlertController.java
Some doc links in the UI of the current release 1.14 are outdated and broken (lead to docs.cryptomator.org/en/1.7). This makes it harder for new users to find (for instance) any info about volume types.
This patch replaces the broken links with the current doc location docs.cryptomator.org
(as has been done in the readme file in [3f7501836967e093839c10d202d8864696d73fbc](https://github.com/Kulesko/cryptomator/commit/3f7501836967e093839c10d202d8864696d73fbc))
> fix broken doc links

- src/main/java/org/cryptomator/ui/preferences/UpdatesPreferencesController.java
In order to see, if users actually using the update link in the preferences, this PR adds UTM parameters to the download URL. It does not contain any personal information, only the current app version is reported.
> Feature: Add UTM parameters to download uri

- src/main/java/org/cryptomator/ui/keyloading/hub/ReceiveKeyController.java
See https://github.com/cryptomator/hub/pull/320
> Send DeviceId to Hub during vault key retrieval

- src/main/resources/css/dark_theme.css
- src/main/resources/css/light_theme.css
Related issue: https://github.com/cryptomator/cryptomator/issues/3726
As discussed, the notification area is now visible with underlined text as visual feedback. The above issue mentioned only “update notification” but I assume all clickable notifications should have the same property, i.e. support and debug notifications as well.
> Add underline effect to clickable notification labels

- src/main/java/org/cryptomator/ui/addvaultwizard/ReadmeGenerator.java
- src/test/java/org/cryptomator/ui/addvaultwizard/ReadMeGeneratorTest.java
This fixes #3252 
The issue was incorrect escaping of unicode characters in the rtf file. I adjusted it to the way this [book](https://www.oreilly.com/library/view/rtf-pocket-guide/9781449302047/ch01.html#character_formatting) recommends.
- for characters < 256 it is recommended to escape using \'xy where xy is the hexadecimal value
- for characters >= 256 it is recommended to escape using \uc1\ux* where x is the decimal value
Maybe the code should be adjusted to meet the second recommendation as well because now only \ux is used. For now I didn't make that adjustment though because it is not related to the reported bug.
> fix unicode escaping for rtf file

- src/main/java/org/cryptomator/ui/mainwindow/MainWindowController.java
fixes #3723 and #3722.
This PR refactors the window-out-of-bounds check (re)added in #3729.
Since during the `@FXML initialize()` method the window is not already displayed, the computations were wrong (e.g. `window.getX()` returnend `NaN`.
To fix this, out-of-bounds computations are now when showing the window. Additionally, a workaround for a Windows pecularity causing to #3723 is added again.
> Refactor: Out-of-bounds-check

- pom.xml
- src/main/java/org/cryptomator/JavaFXUtil.java
- src/main/java/org/cryptomator/common/keychain/KeychainManager.java
- src/main/java/org/cryptomator/ui/keyloading/masterkeyfile/MasterkeyFileLoadingStrategy.java
- src/main/java/org/cryptomator/ui/mainwindow/MainWindowController.java
- src/main/java/org/cryptomator/ui/mainwindow/VaultDetailLockedController.java
- src/main/java/org/cryptomator/ui/preferences/GeneralPreferencesController.java
- src/test/java/org/cryptomator/common/keychain/KeychainManagerTest.java
- src/test/java/org/cryptomator/ui/controls/SecurePasswordFieldTest.java
This PR is a follow up of #3311 and based on work done by @purejava 
It only integrates the TouchID feature for macOS, leaving out any other OS.
The PR adds a new KeychainAccessProvider to securly store passwords in the system by securing the created macOS keychain with addtionaly TouchID query.
The new keychain provider is selected by default on new setups. Existing setups are not migrated. But if the user switches the keychain provider in the preferences, all entries of the old provider are migrated to the new one. The migration is done inside a background thread.
The keychain changes are synchronized on a primitive level, ensuring that only one thread at a time can _change_ entries for a specific keychain and preventing data loss. Quickly changing between the keychain providers creates …
> Feature: TouchID [macOS]

- .github/workflows/av-whitelist.yml
- .github/workflows/win-exe.yml
Due to problems in the Kaspersky upload, the av whitelisting is split in two jobs. Additionally, avast is updated to use SFTP
> CI: Update and split up anti virus whitelisting flow

- src/main/java/org/cryptomator/networking/CombinedKeyStoreSpi.java
- src/main/java/org/cryptomator/networking/SSLContextWithMacKeychain.java
This PR fixes #3834 
This PR adds the `CombinedKeyStoreSpi` class, which is a [`KeyStoreSpi`](https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/security/KeyStoreSpi.html). Its key features are, that it takes two already loaded Keystores and represents a "merge" of those stores. E.g., if `combinedKeyStore.getKey("foobar")` first looks up the key in the first Keystore and if it cannot be found, looks up the key in the second one. The keystore is read-only.
This keystore impl is used for the macOS SSLContextProvider.
> Feature: Use user and system certificate stores on macOS

- .github/workflows/appimage.yml
- .github/workflows/build.yml
- .github/workflows/debian.yml
- .github/workflows/mac-dmg.yml
- .github/workflows/win-exe.yml
This PR improves the CI scripts by only executing those build phases, where files were changed.
E.g. if the pom is adjusted or any Java source code is changed, the build workflow is triggered. If i adjust something for the appimage in the dist folder, the appimage is build.
> CI: Trigger the appropiate build workflows based on changed files

- .github/workflows/appimage.yml
- dist/linux/appimage/build.sh
This PR fixes two issues:
Running this command on different machines only prints out something other than unknown on KUbuntu 24.04 for me.
unknown gets printed out on Arch linux (x86_64 and aarch64), Debian Bookworm (x86_64) and Fedora 42 (aarch64).
`uname -m` prints out the desired value on all the machines mentioned before.
```bash
ralph@arch ~ % uname --help
Usage: uname [OPTION]...
Print certain system information.  With no OPTION, same as -s.
-a, --all                print all information, in the following order,
except omit -p and -i if unknown:
-s, --kernel-name        print the kernel name
-n, --nodename           print the network node hostname
-r, --kernel-release     print the kernel release
-v, --kernel-version     print the kernel version
-m, --machine            print the …
```
> build.sh improvements

- .github/workflows/win-exe.yml
- .github/workflows/winget.yml
- dist/win/build.ps1
Addresses https://github.com/cryptomator/cryptomator/issues/3647.
Depends on https://github.com/cryptomator/integrations-win/pull/106.
<s>Blocked by https://github.com/cryptomator/cryptomator/issues/3824.</s>
Not necessarily blocked, as `liberica` and others can be used. 😄
- Changes to dist build.bat/build.ps1 build scripts: the scripts on `x64` use the openjf `x64` jmods release, whereas the scripts on `arm64` use the JavaFX modules contained in the locally installed JK on the machine, the scripts are running on - tested on both architectures and does work ✅ 
- Changes to the GitHub workflow win-exe.yml: introduce a matrix workflow for the Windows architectures, and liberica `jdk+fx` is used for `arm64` - tested on both architectures and does work ✅
- Taken over changes for Feature: …
> Build installers for Windows ARM64

- src/main/java/org/cryptomator/common/settings/Settings.java
- src/main/java/org/cryptomator/common/settings/SettingsJson.java
- src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultLocationController.java
Fixes #3669
Adds support for automatically saving the previously used custom vault directory, so that new vaults default to the previously used directory.
> Feature: Default to previously used vault directory when creating a vault

- .github/workflows/win-exe.yml
- dist/win/build.ps1
- dist/win/bundle/bundleWithWinfsp.wxs
- dist/win/contrib/patchUpdateCheck.bat
- dist/win/contrib/patchUpdateCheck.ps1
- dist/win/resources/main.wxs
I'd like to disclose that I have used an AI tool to generate this implementation. Since I'm a macOS user, I wasn't able to test it.
My intention of this implementation is allowing the Windows MSI installer to accept a command-line argument (`DISABLEUPDATECHECK`) that configures whether automatic update checks are disabled. This is particularly useful for enterprise deployments where administrators want to control update behavior centrally. And I guess it's also useful for package managers like Chocolatey.
```powershell
msiexec /i Cryptomator-x.y.z.msi DISABLEUPDATECHECK=true /qn
```
```powershell
msiexec /i Cryptomator-x.y.z.msi DISABLEUPDATECHECK=true
```
```powershell
msiexec /i Cryptomator-x.y.z.msi
```
The `DISABLEUPDATECHECK` property accepts the following values:
- **Truthy values** …
> Add Windows MSI installer option to disable update checks via DISABLEUPDATECHECK property
