cryptomator/cryptomator

main/ui/src/main/java/org/cryptomator/ui/MainApplication.java
I don't see another way to fix this unfortunately.
=> OSX bugfix

main/core/src/main/java/org/cryptomator/webdav/WebDavServer.java, main/ui/src/main/java/org/cryptomator/ui/UnlockController.java, main/ui/src/main/java/org/cryptomator/ui/model/Directory.java, main/ui/src/main/java/org/cryptomator/ui/model/DirectoryDeserializer.java, main/ui/src/main/java/org/cryptomator/ui/model/DirectorySerializer.java, main/ui/src/main/resources/fxml/unlock.fxml, main/ui/src/main/resources/localization.properties, main/ui/src/test/java/org/cryptomator/ui/model/DirectoryTest.java
Modification of the context path for the webdav servlet such that the name of the encrypted folder is the last segment of the path. The name will then appear as the name of the network drive on Windows.
I'm not very happy about the modification of the Cryptor interface just to get access to the folder extension. Maybe you could advise here, since you thought up the structure of the project.
=> Pretty network drive names on Windows

main/core/src/main/java/org/cryptomator/webdav/WebDavServer.java, main/pom.xml, main/ui/pom.xml, main/ui/src/main/java/org/cryptomator/ui/MainApplication.java, main/ui/src/main/java/org/cryptomator/ui/MainController.java, main/ui/src/main/java/org/cryptomator/ui/MainModule.java, main/ui/src/main/java/org/cryptomator/ui/UnlockController.java, main/ui/src/main/java/org/cryptomator/ui/UnlockedController.java, main/ui/src/main/java/org/cryptomator/ui/model/Vault.java, main/ui/src/main/java/org/cryptomator/ui/settings/Settings.java, main/ui/src/main/java/org/cryptomator/ui/util/DeferredClosable.java, main/ui/src/main/java/org/cryptomator/ui/util/DeferredCloser.java, main/ui/src/main/java/org/cryptomator/ui/util/FXThreads.java, main/ui/src/main/java/org/cryptomator/ui/util/SingleInstanceManager.java, main/ui/src/test/java/org/cryptomator/ui/MainApplicationTest.java, main/ui/src/test/java/org/cryptomator/ui/util/DeferredCloserTest.java
Removed static resources in WebDavServer, FXThreads and Settings with dependency injection. Replaced static references to MainApplication in the context of closing resources with an injected DeferredCloser. Using controller factory for dependency injection into FX controllers.
=> Dependency injection instead of static instances

main/ui/src/main/resources/localization_fr.properties
French translation added within the Resource Bundle
=> French translation

main/pom.xml, main/ui/pom.xml, main/ui/src/main/java/org/cryptomator/ui/controllers/ChangePasswordController.java, main/ui/src/main/java/org/cryptomator/ui/controllers/InitializeController.java, main/ui/src/main/java/org/cryptomator/ui/controllers/WelcomeController.java, main/ui/src/main/java/org/cryptomator/ui/util/PasswordStrengthUtil.java, main/ui/src/main/resources/fxml/change_password.fxml, main/ui/src/main/resources/fxml/initialize.fxml, main/ui/src/main/resources/fxml/welcome.fxml, main/ui/src/main/resources/localization.properties, main/ui/src/main/resources/localization_fr.properties
Password strength indicator added in the "initialize" and in the "change password" windows.
=> Implementation of issue #198

main/ui/src/main/resources/localization/fr.txt
Hello,
Here is some translation enhancement for French.
Regards,
=> Enhanced fr translation

README.md
I think it would be nice to promote other Open Source solutions which use standards such as WebDAV and work well with Cryptomator.
=> Add that the solution works with Open Source clouds

README.md
Cryptomator is used by many ownCloud users and the interview and installation guidance was well received.
=> Add ownCloud

main/commons/src/main/java/org/cryptomator/common/settings/VaultSettings.java, main/commons/src/main/java/org/cryptomator/common/settings/VaultSettingsJsonAdapter.java, main/ui/src/main/java/org/cryptomator/ui/controllers/UnlockController.java, main/ui/src/main/resources/fxml/unlock.fxml, main/ui/src/main/resources/localization/en.txt
See https://github.com/cryptomator/cryptomator/issues/375
This change only covers task 2, meaning the new setting is not used yet.
I have done some manual testing to check that it is working.
=> Add read-only option to the advanced settings

main/ui/src/main/java/org/cryptomator/ui/model/Vault.java
See #375
This change covers the third task.
=> Unlock vault with readonly flag if requested (second attempt)

main/keychain/pom.xml, main/keychain/src/main/java/org/cryptomator/keychain/KeychainModule.java, main/keychain/src/main/java/org/cryptomator/keychain/LinuxSecretServiceAccess.java, main/keychain/src/test/java/org/cryptomator/keychain/TestKeychainModule.java
Add access functionality for GNOME default keyring
=> Implement save password working on Linux

main/ui/src/main/java/org/cryptomator/ui/controls/SecPasswordField.java
Set text in password fields to null when they get swiped
=> Fixes https://github.com/cryptomator/cryptomator/issues/887

main/buildkit/assembly-linux.xml, main/buildkit/pom.xml, main/keychain/pom.xml, main/keychain/src/main/java/org/cryptomator/keychain/GnomeKeyringAccess.java, main/keychain/src/main/java/org/cryptomator/keychain/GnomeKeyringAccessImpl.java, main/keychain/src/main/java/org/cryptomator/keychain/KeychainModule.java, main/keychain/src/main/java/org/cryptomator/keychain/LinuxKeychainTester.java, main/keychain/src/main/java/org/cryptomator/keychain/LinuxSecretServiceAccess.java, main/keychain/src/test/java/org/cryptomator/keychain/TestKeychainModule.java
Please be so kind to use the `secret-service-simple` branch from me and delete `feature/422-save-pw-linux` on your repo, as I squashed some of my earlier commits. The contained code (for the squashed commits) is unchanged.
=> Fixes https://github.com/cryptomator/cryptomator/issues/422

main/ui/src/main/java/org/cryptomator/ui/addvaultwizard/AddVaultModule.java, main/ui/src/main/java/org/cryptomator/ui/changepassword/ChangePasswordModule.java, main/ui/src/main/java/org/cryptomator/ui/forgetPassword/ForgetPasswordModule.java, main/ui/src/main/java/org/cryptomator/ui/fxapp/FxApplicationModule.java, main/ui/src/main/java/org/cryptomator/ui/mainwindow/MainWindowModule.java, main/ui/src/main/java/org/cryptomator/ui/migration/MigrationModule.java, main/ui/src/main/java/org/cryptomator/ui/preferences/PreferencesModule.java, main/ui/src/main/java/org/cryptomator/ui/quit/QuitModule.java, main/ui/src/main/java/org/cryptomator/ui/recoverykey/RecoveryKeyModule.java, main/ui/src/main/java/org/cryptomator/ui/removevault/RemoveVaultModule.java, main/ui/src/main/java/org/cryptomator/ui/unlock/UnlockModule.java, main/ui/src/main/java/org/cryptomator/ui/vaultoptions/VaultOptionsModule.java, main/ui/src/main/java/org/cryptomator/ui/wrongfilealert/WrongFileAlertModule.java
The image quality of the window icon at taskbar is quite low.
This patch add multiple icons with different sizes and let the system choose the best one.
=> Add multiple icons and let system choose the best size

main/ui/src/main/java/org/cryptomator/ui/controls/SecurePasswordField.java
=> Allow password field to be cleared with Ctrl/Command + backspace

main/keychain/src/main/java/org/cryptomator/keychain/KeychainAccess.java, main/keychain/src/main/java/org/cryptomator/keychain/LinuxSecretServiceKeychainAccess.java, main/keychain/src/main/java/org/cryptomator/keychain/LinuxSecretServiceKeychainAccessImpl.java, main/keychain/src/main/java/org/cryptomator/keychain/MacSystemKeychainAccess.java, main/keychain/src/main/java/org/cryptomator/keychain/WindowsProtectedKeychainAccess.java, main/keychain/src/test/java/org/cryptomator/keychain/MapKeychainAccess.java, main/ui/src/main/java/org/cryptomator/ui/changepassword/ChangePasswordController.java
=> Implement changePassphrase from the secret-service API

main/keychain/src/main/java/org/cryptomator/keychain/KeychainAccessStrategy.java, main/keychain/src/main/java/org/cryptomator/keychain/LinuxKDEWalletKeychainAccessImpl.java, main/pom.xml, main/ui/src/main/resources/license/THIRD-PARTY.txt
=> Evade DBusException

main/ui/src/main/resources/i18n/strings_hu.properties
=>  New translations strings.properties (Hungarian)

.github/workflows/build.yml, .idea/misc.xml, README.md, main/commons/src/main/java/org/cryptomator/common/CommonsModule.java, main/commons/src/main/java/org/cryptomator/common/LicenseChecker.java, main/commons/src/main/java/org/cryptomator/common/settings/VaultSettings.java, main/commons/src/main/java/org/cryptomator/common/vaults/Vault.java, main/commons/src/main/java/org/cryptomator/common/vaults/VaultListChangeListener.java, main/commons/src/main/java/org/cryptomator/common/vaults/VaultListManager.java, main/commons/src/test/java/org/cryptomator/common/EnvironmentTest.java, main/commons/src/test/java/org/cryptomator/common/LicenseCheckerTest.java, main/commons/src/test/java/org/cryptomator/common/settings/SettingsJsonAdapterTest.java, main/launcher/src/main/java/org/cryptomator/launcher/FileOpenRequestHandler.java, main/launcher/src/main/java/org/cryptomator/logging/LoggerModule.java, main/pom.xml, main/ui/src/main/java/org/cryptomator/ui/common/DefaultSceneFactory.java, main/ui/src/main/java/org/cryptomator/ui/unlock/UnlockWorkflow.java, main/ui/src/test/java/org/cryptomator/ui/recoverykey/RecoveryKeyFactoryTest.java
This not only allows us to use some new language features, it might also fix some upstream bugs:
- fixes #1245
- potentially #1469
- potentially #1465
=> Update to JDK 16

README.md, main/ui/src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultLocationController.java, main/ui/src/main/java/org/cryptomator/ui/addvaultwizard/LocationPresets.java, main/ui/src/main/resources/fxml/addvault_new_location.fxml
=> Add MEGA & pCloud providers to vault location presets

README.md
Congrats! Keep up the great work.
=> consistency bump

pom.xml, src/main/java/org/cryptomator/ui/controls/SecurePasswordField.java
Update OpenJFX to version 17.0.0.1
Fixes #1242 
Fixes #1591 
Fixes #1153
=> Update to OpenJFX 17

dist/win/build.bat, dist/win/build.ps1, dist/win/resources/customWizard.wxi, dist/win/resources/main.wxs, dist/win/resources/overrides.wxi
For easier debugging, the windows powershell build script is parameterized now.
The pwsh script needs additional parameters, so to create a full fletched installer, one has to run the batch file (`/dist/win/build.bat`).
=> Parameterize local windows build script

dist/win/contrib/patchWebDAV.bat, dist/win/contrib/patchWebDAV.ps1
please also run this (manually, no need to run via installer), as this is untested 🙈
=> parameterize patchWebDAV.ps1 and add default values to .bat file

src/main/java/org/cryptomator/ui/mainwindow/WelcomeController.java, src/main/java/org/cryptomator/ui/migration/MigrationImpossibleController.java, src/main/java/org/cryptomator/ui/wrongfilealert/WrongFileAlertController.java
closes: #2315 
updated links from 1.5 to 1.6 (the latest version) in three separate instances.
PS: not sure if there are more links to update if so please share the filenames/ locations.
=> updated links to the latest version.

dist/linux/appimage/resources/AppDir/bin/cryptomator.sh, dist/linux/debian/cryptomator.sh
Hopefully this fixes #2301. Unfortunately I did not find the time to create an AppImage manually and test the change.
If the PR needs adjustments, please let me know.
=> Pass on CLI parameters from launch scripts to executables

src/main/java/org/cryptomator/ui/traymenu/TrayMenuBuilder.java
=> Use 2x icon on Mac menu bar (#2345)

pom.xml, src/main/java/org/cryptomator/common/CommonsModule.java, src/main/java/org/cryptomator/common/LicenseHolder.java, src/main/java/org/cryptomator/common/settings/VaultSettings.java, src/main/java/org/cryptomator/common/vaults/Vault.java, src/main/java/org/cryptomator/common/vaults/VaultModule.java, src/main/java/org/cryptomator/ui/addvaultwizard/CreateNewVaultPasswordController.java, src/main/java/org/cryptomator/ui/common/NewPasswordController.java, src/main/java/org/cryptomator/ui/controls/NiceSecurePasswordField.java, src/main/java/org/cryptomator/ui/health/CheckDetailController.java, src/main/java/org/cryptomator/ui/health/CheckListCellController.java, src/main/java/org/cryptomator/ui/health/ResultListCellController.java, src/main/java/org/cryptomator/ui/keyloading/masterkeyfile/PassphraseEntryController.java, src/main/java/org/cryptomator/ui/mainwindow/ResizeController.java, src/main/java/org/cryptomator/ui/mainwindow/VaultDetailController.java, src/main/java/org/cryptomator/ui/mainwindow/VaultDetailLockedController.java, src/main/java/org/cryptomator/ui/mainwindow/VaultListCellController.java, src/main/java/org/cryptomator/ui/mainwindow/VaultListContextMenuController.java, src/main/java/org/cryptomator/ui/migration/MigrationRunController.java, src/main/java/org/cryptomator/ui/vaultoptions/MasterkeyOptionsController.java, src/test/java/org/cryptomator/common/settings/VaultSettingsTest.java
Due to some [new API](https://bugs.openjdk.org/browse/JDK-8274771) in OpenJFX 19, we can now replace some (not all) bindings that have previously used EasyBind.
This needs extensive UI testing.
=> Update to OpenJFX 19

pom.xml, src/main/java/org/cryptomator/ui/controls/FontAwesome5Icon.java, src/main/java/org/cryptomator/ui/health/CheckDetailController.java, src/main/java/org/cryptomator/ui/health/CheckExecutor.java, src/main/java/org/cryptomator/ui/health/CheckStateIconView.java, src/main/java/org/cryptomator/ui/health/Result.java, src/main/java/org/cryptomator/ui/health/ResultFixApplier.java, src/main/java/org/cryptomator/ui/health/ResultListCellController.java, src/main/resources/fxml/health_check_details.fxml, src/main/resources/fxml/health_check_list.fxml, src/main/resources/fxml/health_start.fxml, src/main/resources/i18n/strings.properties
This PR enhances the health check with the following features:
* A fix all button for results of severity INFO (closes #2483)
* Filter for the result list (filters are severity and fix state)
* Tooltip explaining the result severity
* Contextmenu to copy a single result
Screenshots:
Health Vault
Tooltip and activated FixAll button
Filter
=> Improve Health Check

pom.xml, src/main/java/org/cryptomator/ui/traymenu/AwtTrayMenuController.java, src/main/java/org/cryptomator/ui/traymenu/TrayMenuBuilder.java
Now tracking unlockedness and updating the icon accordingly.
=> Unlocked status indicator in tray icon #2557

src/main/resources/fxml/migration_start.fxml, src/main/resources/i18n/strings.properties
Addresses issue #1897. Open to further improvements!
=> Add more info to Migration Screen

.github/workflows/appimage.yml, dist/linux/appimage/build.sh, dist/linux/debian/rules
Fixes https://github.com/cryptomator/cryptomator/issues/2640.
=> Add jdk.security.auth module as it's required by dbus-java-core

.github/workflows/appimage.yml, .github/workflows/build.yml, .github/workflows/debian.yml, .github/workflows/get-version.yml, .github/workflows/mac-dmg.yml, .github/workflows/pullrequest.yml, .github/workflows/release-check.yml, .github/workflows/win-exe.yml, .idea/misc.xml, dist/linux/debian/control, dist/linux/debian/rules, dist/win/resources/main.wxs, pom.xml, src/main/java/org/cryptomator/ipc/IpcMessage.java, src/main/java/org/cryptomator/ipc/IpcMessageListener.java, src/main/java/org/cryptomator/ui/health/StartController.java, src/main/java/org/cryptomator/ui/traymenu/AwtTrayMenuController.java, src/main/java/org/cryptomator/ui/unlock/UnlockInvalidMountPointController.java
=> Upgrade to jdk20 and jfx20

src/main/java/org/cryptomator/ui/mainwindow/VaultListController.java, src/main/resources/fxml/vault_list.fxml
In addition to #3082, this modification will resolve the actual issue with the add vault button by separating the context menu from it.
=> Fix addVaultButton misbehavior

.github/workflows/appimage.yml, .github/workflows/build.yml, .github/workflows/debian.yml, .github/workflows/dependency-check.yml, .github/workflows/mac-dmg.yml, .github/workflows/pullrequest.yml, .github/workflows/release-check.yml, .github/workflows/win-exe.yml, dist/linux/appimage/build.sh, dist/mac/dmg/build.sh, dist/win/build.ps1
Fixes https://github.com/cryptomator/cryptomator/issues/3453
=> JavaFX Workaround: Set `javafx.platform` property in scripts

dist/linux/appimage/build.sh
=> Fix typo in AppImage build.sh

.github/workflows/appimage.yml, .github/workflows/debian.yml, .github/workflows/mac-dmg.yml, .github/workflows/win-exe.yml
Updates release builds to use JDK 22.0.2+9
=> Feature: JDK 22.0.2+9 for release artifacts

src/main/java/org/cryptomator/launcher/SupportedLanguages.java, src/main/resources/i18n/strings_ug.properties
translate: Add Uyghur Language Translation to this repo
tested on windows platform
=> translate: Add Uyghur Language Translation

.github/CONTRIBUTING.md
Correct the link of issues list for both iOS and Android.
=> Correct the link of issues list for both iOS and Android.

src/main/java/org/cryptomator/ui/mainwindow/VaultListCellController.java, src/main/resources/fxml/vault_list_cell.fxml
This PR adjusts the top and bottom insets of VaultListCells in compact mode, reducing padding to improve layout consistency.
=> Fix VaultListCell Padding in Compact Mode

src/main/java/org/cryptomator/ui/mainwindow/MainWindowController.java
For more info, see #3091.
Related to #3722.
=> Feature: readd out of bounds check

src/main/java/org/cryptomator/ui/dialogs/SimpleDialog.java, src/main/java/org/cryptomator/ui/dialogs/SimpleDialogController.java, src/main/resources/fxml/simple_dialog.fxml
This change allows the SimpleDialog to be displayed with only one button. 
To achieve this, the TextKey no longer needs to be set. When the cancelButtonKey is not defined, the cancel button is automatically hidden, leaving only the ok button visible.
=> Feature: Simple Dialog with one Button

pom.xml, src/main/java/org/cryptomator/common/keychain/KeychainManager.java, src/main/java/org/cryptomator/ui/preferences/GeneralPreferencesController.java, src/test/java/org/cryptomator/common/keychain/MapKeychainAccess.java
adjust classes to new keychain api.
=> Bump integrations-libs to api level 1.6.0

.github/workflows/appimage.yml, .github/workflows/aur.yml
This PR adds a new workflow to the repository: AUR release automation
The workflow is started by a published release or manually. In the latter case the release tag must be specified. It works similarly to the flathub release workflow:
1. Create a branch in the AUR repo
2. Update the PKGBUILD file with release archive url and checksum
3. Generate the .SRCINFO file
4. Push changes
5. Create PR
6. Notify about the PR
=> Feature: Automate AUR release

.github/workflows/win-exe.yml, dist/win/build.ps1, dist/win/contrib/patchUpdateCheck.ps1, dist/win/contrib/patchWebDAV.bat, dist/win/resources/main.wxs
This PR adjusts the Windows installer build.
The two main parts are:
* decouple patchUpdateCheck script from app name
* simplify patchWebdav script and align it with patchUpdate
=> Feature: Refactoring for Windows installer build
